# This code is part of Qiskit.
#
# (C) Copyright IBM 2026.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

"""Typed, MCP-independent contracts for the Runtime research core."""

from .artifacts import ArtifactSink, LocalArtifactCAS, artifactize
from .batches import (
    BatchContractError,
    BatchLifecycle,
    BatchLimitError,
    DuplicatePolicy,
    DuplicateSubmissionError,
    SubmissionReceiptRegistry,
    plan_batch_partitions,
)
from .circuits import (
    CircuitBoundaryResult,
    CircuitContractError,
    CircuitFormatError,
    CircuitIsaError,
    CircuitLimitError,
    CircuitLimits,
    CircuitValidationReport,
    CircuitWidthError,
    IngestedCircuit,
    IsaValidationIssue,
    ResolvedTarget,
    TargetIdentityError,
    apply_circuit_mode,
    ingest_circuit,
    load_circuit_artifact,
    target_fingerprint,
    validate_circuit_isa,
)
from .models import (
    LOCKED_BATCH_INTERACTIVE_TTL_SECONDS,
    LOCKED_MAX_BATCH_TTL_SECONDS,
    LOCKED_MAX_JOB_EXECUTION_SECONDS,
    ApprovalReceipt,
    ArtifactRef,
    BackendSnapshot,
    BackendStatusSnapshot,
    BatchExecutionLimits,
    BatchJobReceipt,
    BatchJobStatus,
    BatchJobUsage,
    BatchReference,
    BatchStatus,
    BatchSubmissionFailure,
    BatchSubmissionReceipt,
    BatchUsage,
    CalibrationDatum,
    CircuitArtifact,
    CircuitProvenance,
    CircuitRegister,
    EstimatorPubResult,
    EstimatorPubSpec,
    FaultyInstruction,
    InlineJsonValue,
    InstructionSnapshot,
    PauliObservables,
    ParameterBindings,
    PrimitiveResultEnvelope,
    ProcessorMetadata,
    PubExecutionEstimate,
    QubitSnapshot,
    RuntimeUsage,
    RecoveredSubmissionStatus,
    SamplerPubResult,
    SamplerPubSpec,
    ShapedResultValue,
    SparsePauliHamiltonian,
    SubmissionPartition,
    SubmissionPlan,
    SubmissionKeyStatus,
    TargetMetadata,
)
from .primitives import (
    PrimitiveContractError,
    SubmittedPrimitiveJob,
    inline_value,
    parse_primitive_result,
    prepare_estimator_pubs,
    prepare_sampler_pubs,
    submit_estimator_pubs,
    submit_sampler_pubs,
)
from .serialization import canonical_json, canonical_json_hash, to_json_safe
from .snapshots import (
    FractionalGateMode,
    SnapshotContractError,
    build_backend_snapshot,
    resolve_backend_snapshot,
    snapshot_content_hash,
    target_content_hash,
    validate_snapshot_request,
)


__all__ = [
    "ApprovalReceipt",
    "ArtifactRef",
    "ArtifactSink",
    "BatchContractError",
    "BatchExecutionLimits",
    "BatchJobReceipt",
    "BatchJobStatus",
    "BatchJobUsage",
    "BatchLifecycle",
    "BatchLimitError",
    "BatchReference",
    "BackendSnapshot",
    "BackendStatusSnapshot",
    "BatchStatus",
    "BatchSubmissionFailure",
    "BatchSubmissionReceipt",
    "BatchUsage",
    "CalibrationDatum",
    "CircuitArtifact",
    "CircuitBoundaryResult",
    "CircuitContractError",
    "CircuitFormatError",
    "CircuitIsaError",
    "CircuitLimitError",
    "CircuitLimits",
    "CircuitProvenance",
    "CircuitRegister",
    "CircuitValidationReport",
    "CircuitWidthError",
    "EstimatorPubResult",
    "EstimatorPubSpec",
    "FaultyInstruction",
    "InlineJsonValue",
    "InstructionSnapshot",
    "IngestedCircuit",
    "IsaValidationIssue",
    "LocalArtifactCAS",
    "PauliObservables",
    "ParameterBindings",
    "PrimitiveContractError",
    "PrimitiveResultEnvelope",
    "ProcessorMetadata",
    "PubExecutionEstimate",
    "QubitSnapshot",
    "ResolvedTarget",
    "RecoveredSubmissionStatus",
    "RuntimeUsage",
    "SamplerPubResult",
    "SamplerPubSpec",
    "ShapedResultValue",
    "SparsePauliHamiltonian",
    "SubmissionPartition",
    "SubmissionPlan",
    "SubmissionKeyStatus",
    "SubmissionReceiptRegistry",
    "SubmittedPrimitiveJob",
    "TargetMetadata",
    "TargetIdentityError",
    "FractionalGateMode",
    "SnapshotContractError",
    "DuplicatePolicy",
    "DuplicateSubmissionError",
    "LOCKED_BATCH_INTERACTIVE_TTL_SECONDS",
    "LOCKED_MAX_BATCH_TTL_SECONDS",
    "LOCKED_MAX_JOB_EXECUTION_SECONDS",
    "artifactize",
    "apply_circuit_mode",
    "build_backend_snapshot",
    "canonical_json",
    "canonical_json_hash",
    "ingest_circuit",
    "inline_value",
    "load_circuit_artifact",
    "parse_primitive_result",
    "plan_batch_partitions",
    "prepare_estimator_pubs",
    "prepare_sampler_pubs",
    "resolve_backend_snapshot",
    "snapshot_content_hash",
    "target_fingerprint",
    "target_content_hash",
    "to_json_safe",
    "submit_estimator_pubs",
    "submit_sampler_pubs",
    "validate_circuit_isa",
    "validate_snapshot_request",
]
